
const ERRORS={
    "ERROR_AL_OBTENER_ULTIMO_ID":1,
    "ERROR_AL_INSERTAR_KEY":2,
    "ERROR_AL_RECUPERAR_KEY":3,
    "NO_EXISTE_ELEMENTO_BUSCADO":4,
    "ERROR_AL_BORRAR_KEY":5,
    "ERROR_AL_ACTUALIZAR_KEY":6,
}

const STATUS_CODES={
"OK":200,
"CREATED":201,
"NO_CONTENT":204,
"UNATHORIZED":401,
"INTERNAL_SERVER_ERROR":500,

}
module.exports ={ERRORS, STATUS_CODES}